마커 애니메이션 수정
boostcamp-2020/Project17-A-Map pull request #34
Opened 2020-11-30 10:07 UTC by yskpth91

- 기존에는 군집돼있던 마커들에 포함돼있는 모든 POI들을 애니메이션 시켰는데, 화면에 있는 마커들만 애니메이션이 되게 수정.
- 애니메이션이 되는 조건 추가
  - 줌레벨이 바뀔때 && 화면의 마커 개수가 바뀔 때

2020-11-30 16:09 UTC, SkydevilK requested changes

2020-11-30 16:09 UTC, SkydevilK commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +                    self.zoomLevel = self.mapView.zoomLevel
위의 리뷰 정정하겠습니다. 여기서 해주네요.
그런데 현재 여기는 마커들을 그리는 곳입니다. 
줌 레벨을 변경하시려면 밑의 mapViewCameraIdle 부분에서 해주셔야 조금 더 코드가 좋아질 것 같습니다.

2020-11-30 16:09 UTC, SkydevilK commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +                let distance = sqrt(pow(beforeMarker.position.lat - clusterMarker.position.lat, 2) + pow(beforeMarker.position.lng - clusterMarker.position.lng, 2))
저희팀이 유독 거리 구하는 부분을 함수화 안하고 계속 중복되게 쓰는게 보이네요.
이 부분은 extention으로 빼거나 static function으로 만들어서 중복되는 코드를 줄여봅시다. 오늘 회의에서 말해봐요.

2020-11-30 16:09 UTC, SkydevilK commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +            markerView.frame.origin = CGPoint(x: -100, y: -100)
이부분에서 markerView의 origin을 -100, -100 하시는 이유는 Animation의 출발 위치를 잡으려고 하시는 것으로 생각됩니다. 그런데 이렇게 되면 애니메이션 시작할 때 조금 부자연스러워지지 않을까 사료됩니다. 0,0에서 출발 하지 않으면 생기는 문제점이 있을까요?

2020-11-30 16:15 UTC, yskpth91 commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +            markerView.frame.origin = CGPoint(x: -100, y: -100)
아아 -100으로 잡은건 이슈에 올려뒀던 잔상 문제 때문이었습니다. 현재 애니메이션은 layer가 애니메이션이 되기때문에 마커뷰는 애니메이션할때 사용되지 않아요 :) 
백그라운드 스레드에서 마커뷰를 슈퍼뷰로부터 지워주는게 있는데 그때 뭔가 백그라운드 스레드에서 마커뷰를 지워주는 속도가 느려 잔상이 남는거 처럼 보여서 아예 생성할 때 안보이는 곳으로 생성을 해주어 버그를 해결했습니다

2020-11-30 16:16 UTC, yskpth91 commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +                let distance = sqrt(pow(beforeMarker.position.lat - clusterMarker.position.lat, 2) + pow(beforeMarker.position.lng - clusterMarker.position.lng, 2))
동의합니다! 내일 회의때 한번 얘기해봐요 :)

2020-11-30 16:19 UTC, yskpth91 commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +                    self.zoomLevel = self.mapView.zoomLevel
아아 첨에는 mapViewCameraIdle에서 처리를 해주었는데요 기존에 존재하고 있던 클러스터 마커들과 새로 군집된 클러스터 마커들을 비교 후 애니메이션을 줘야해서 줌레벨을 변경하는 코드가 self.clusterMarkers.append(marker) 이후로 갔습니다 ㅠ

2020-11-30 16:20 UTC, SkydevilK commented on NaverMapA/NaverMapA/Controller/MainViewController.swift
> +            markerView.frame.origin = CGPoint(x: -100, y: -100)
마커뷰를 지워주는 함수는 56~58 줄에 있는 부분 아닌가요?? 해당 로직상 for문이 다 돌고 지워지는 것으로 알고 있습니다 @_@

2020-12-01 01:05 UTC, kyungpyoda approved these changes

2020-12-01 08:44 UTC, hoonv approved these changes

2020-12-01 09:41 UTC, merged